name: Setup JavaScript
description: Setup JavaScript environment

inputs:
  persist-credentials:
    description: Whether to configure the token or SSH key with the local git config
    default: false

  ref:
    description: The `ref` option of actions/checkout
    default: ""

  fetch-all:
    description: Whether to fetch all commits and submodules.
    default: false

  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    default: "lts/*"

  auto-install:
    description: Whether to automatically install dependencies.
    default: true

  package-manager:
    description: "Package manager to use. Examples: npm, yarn, pnpm. Leave empty to auto-detect."
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: ${{ inputs.persist-credentials }}
        ref: ${{ inputs.ref }}
        fetch-depth: "${{ inputs.fetch-all == 'true' && '0' || '1' }}"
        submodules: "${{ inputs.fetch-all == 'true' && 'recursive' || false }}"

    - name: Auto detect package manager
      id: detect
      shell: bash
      run: |
        if [[ -n "${{ inputs.package-manager }}" ]]; then
          echo "pm=${{ inputs.package-manager }}" >> $GITHUB_OUTPUT
          exit 0
        fi

        if [[ -f "pnpm-lock.yaml" ]]; then
          echo "pm=pnpm" >> $GITHUB_OUTPUT
        elif [[ -f "yarn.lock" ]]; then
          echo "pm=yarn" >> $GITHUB_OUTPUT
        elif [[ -f "package-lock.json" ]]; then
          echo "pm=npm" >> $GITHUB_OUTPUT
        else
          echo "No lock file found. Defaulting to pnpm."
          echo "pm=pnpm" >> $GITHUB_OUTPUT
        fi

    - name: Install pnpm
      if: ${{ steps.detect.outputs.pm == 'pnpm' }}
      uses: pnpm/action-setup@v4

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ steps.detect.outputs.pm }}
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      if: ${{ inputs.auto-install == 'true' }}
      shell: bash
      run: |
        echo "Using package manager: ${{ steps.detect.outputs.pm }}"
        ${{ steps.detect.outputs.pm }} install
